#!/bin/sh
export RUNGROOVY=`which run-groovy`
. `dirname $RUNGROOVY`/env.sh 

export CLAS12DIR=`dirname $RUNGROOVY`/..
 
#--------------------------------------------------------------
# Adding supporting COAT jar files
for i in `ls -a $CLAS12DIR/lib/clas/*.jar`
do  
#echo "$i"
if [ -z "${JYPATH}" ] ; then
JYPATH="$i"
else
JYPATH=${JYPATH}:"$i"
fi
done 
#--------------------------------------------------------------
# Adding supporting plugins directory
for i in `ls -a $CLAS12DIR/lib/services/*.jar`
do
if [ -z "${JYPATH}" ] ; then
JYPATH="$i"
else
JYPATH=${JYPATH}:"$i"
fi
done
#--------------------------------------------------------------
# Adding supporting plugins directory
#--------------------------------------------------------------
# Done loading plugins
#--------------------------------------------------------------
# Adding supporting plugins directory 
for i in `ls -a $CLAS12DIR/lib/utils/*.jar`
do
if [ -z "${JYPATH}" ] ; then
JYPATH="$i"
else
JYPATH=${JYPATH}:"$i"
fi
done
#-------------------------------------------------------------
JYPATH=${JYPATH}:${CLAS12DIR}/lib/packages
echo " "
echo " "
echo "*****************************************"
echo "*    Running COAT-JAVA Groovy Scripts   *"
echo "*    Version : 3a  Release : 2016       *" 
echo "*****************************************"
echo " "
echo " "
export JAVA_OPTS="-Dsun.java2d.pmoffscreen=false -Xms32m -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:InitiatingHeapOccupancyPercent=80"
groovy -cp "$JYPATH" $*
